BMNC/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import bmnc_news.urls as bmnc_news
import bmnc_sign_up.urls as bmnc_sign_up
from django.views.generic.base import RedirectView

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^news/', include(bmnc_news,namespace='bmnc-news')),
    url(r'^home/', include(bmnc_sign_up,namespace='bmnc-home')),
    url(r'^$', RedirectView.as_view(url="/home/", permanent='true'),name='index')
]

bmnc_news/urls.py
from django.conf.urls import url
from .views import index, history, profile

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^history/$', history, name='history'),
    url(r'^profile/$', profile, name='profile')

]

bmnc_sign_up/urls.py
from django.conf.urls import url
from .views import index,index2

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^index2/$', index2, name='index2')
]

bmnc_news/models.py
from django.db import models, connection
# from bmnc_sign_up.models import Universitas, Dosen, Staf, Mahasiswa, Narasumber

# Create your models here.

# class Polling(models.Model):
#     id_p = models.IntegerField(primary_key=True)
#     polling_start = models.DateField()
#     polling_end = models.DateField()
#     total_responden = models.IntegerField()

# class Polling_Biasa(models.Model):
#     id_polling = models.ForeignKey(Polling, on_delete=models.CASCADE, primary_key=True)
#     url = models.CharField(max_length=50)
#     deskripsi = models.CharField(max_length=100)

# class Berita(models.Model):
#     id_b = models.CharField(max_length=50, primary_true=True)
#     judul = models.CharField(max_length=100)
#     topik = models.CharField(max_length=100)
#     created_at = models.DateField()
#     updated_at = models.DateField()
#     jumlah_kata = models.IntegerField()
#     rerata_rating = models.DecimalField(max_digits=5, decimal_places=2)
#     id_univeritas = models.ForeignKey(Universitas, on_delete=models.CASCADE)

# class Narasumber_Berita(models.Model):
#     url_berita = models.ForeignKey(Berita, on_delete=models.CASCADE, primary_key=True)
#     id_narasumber = models.ForeignKey(Narasumber, on_delete=models.CASCADE, primary_key=True)

bmnc_sign_up/models.py
from django.db import models, connection

# Create your models here.

# class Universitas(models.Model):
#     id_u = models.IntegerField(primary_key=True)
#     jalan = models.CharField(max_length=100)
#     kelurahan = models.CharField(max_length=50)
#     provinsi = models.CharField(max_length=50)
#     kodepos = models.CharField(max_length=10)
#     website = models.CharField(max_length=50)
    
# class Narasumber(models.Model):
#     id_n = models.IntegerField(primary_key=True)
#     nama = models.CharField(max_length=50)
#     email = models.CharField(max_length=50)
#     tempat = models.CharField(max_length=50)
#     tanggal = models.DateField()
#     no_hp = models.CharField(max_length=50)
#     jumlah_berita = models.IntegerField()
#     rerata_kata = models.IntegerField()
#     id_universitas = models.ForeignKey(Universitas, on_delete=models.CASCADE)

# class Dosen(models.Model):
#     id_narasumber = models.ForeignKey(Narasumber, on_delete=models.CASCADE, primary_key=True)
#     nik_dosen = models.CharField(max_length=20)
#     jurusan = models.CharField(max_length=50)

# class Mahasiswa(models.Model):
#     id_narasumber = models.ForeignKey(Narasumber, on_delete=models.CASCADE, primary_key=True)
#     npm = models.CharField(max_length=20)
#     status = models.CharField(max_length=20)

# class Staf(models.Model):
#     id_narasumber = models.ForeignKey(Narasumber, on_delete=models.CASCADE, primary_key=True)
#     nik_staf = models.CharField(max_length=20)
#     posisi = models.CharField(max_length=20)

bmnc_news/views.py
from django.shortcuts import render

response = {'author': 'BMNC14B'}
def index(request) :
    html = 'bmnc_news/news.html'
    return render(request, html, response)

def history(request) :
    html = 'bmnc_news/riwayat.html'
    return render(request, html, response)

def profile(request) :
    html = 'bmnc_news/profile.html'
    return render(request, html, response)

bmnc_sign_up/views.py
from django.shortcuts import render

response = {'author': 'BMNC14B'}
def index(request) :
    html = 'bmnc_sign_up/sign_up.html'
    return render(request, html, response)

def index2(request):
    html = 'bmnc_sign_up/cobacoba.html'
    return render(request, html, response)
    
    

bmnc_news/templates/bmnc_news/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Home">
    <meta name="author" content="{{author}}">

    <title>
        {% block title %} BMNC By {{author}} {% endblock %}
    </title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bmnc_news.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

</head>

<body>
    <header>
        {% include "bmnc_news/partials/header.html" %}
    </header>
    <content>
            {% block content %}

            {% endblock %}
    </content>
    <footer>

        {% block footer %}
        {% include "bmnc_news/partials/footer.html" %}
        {% endblock %}

    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/bmnc_news.js' %}"></script>

    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

bmnc_news/templates/bmnc_news/news.html
{% extends "bmnc_news/layout/base.html" %}

{% block content %}
<div class="py-5" style="margin-top: -50px">
    <div class="container">
        <div class="col-md-10">
        <h2 class="text-primary"style="font-family:Raleway">Colosseum Roma, Salah Satu Keajaiban Dunia dengan Arsitektur yang Memikat</h2>
        <h5 style="font-family:Raleway"><span class="glyphicon glyphicon-user"></span><a href=""> bintang_ilham</a> &#9675; Harvard University &#9675; Posted at 2018-05-05 14:30</h5>
        <p class="" style="text-align: justify; text-justify: inter-word;font-family:Raleway">Colosseum yang merupakan salah satu dari 7 keajaiban dunia dibangun pada tahun 72 Masehi oleh
                kaisar Romawi yang bernama Vespasian dari dinasti Flavian. Atas perintah Vespasian,
                Colosseum dibangun oleh para arsitek, seniman Romawi dan para budak Yahudi. Pembangunannya
                kemudian dilanjutkan oleh penerusnya yang bernama Titus hingga akhirnya diresmikan pada tahun
                82 Masehi dengan kapasitas sekitar 50.000 penonton.</p>
        </div>
        <div class="col-md-10">
        <h2 class="text-primary"style="font-family:Raleway">Brandenburg Gate</h2>
        <h5style="font-family:Raleway"><span class="glyphicon glyphicon-user"></span><a href=""> rio_kurtinus</a> &#9675; University of Indonesia &#9675;  Posted at 2018-05-05 20:30</h5>
        <p class="" style="text-align: justify; text-justify: inter-word;font-family:Raleway">Bila Checkpoint Charlie adalah simbol pemisah Berlin Barat dan Timur,
            Brandenburg Gate justru sebaliknya. Ketika Tembok Berlin runtuh pada bulan November 1989,
            tempat yang dibangun pada tahun 1788-1791 ini dijadikan sebagai simbol bersatunya Berlin Barat dan
            Timur. Di Brandenburg Gate, Anda bisa menyaksikan aksi artis jalanan,
            misalnya seperti orang-orang yang berpakaian tentara Jerman.</p>
        </div>
    </div>
</div>

<div class="py-5" style="margin-left: 550px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <ul class="pagination" >
                <li class="page-item">
                <a class="page-link" href="#">
                <span>«</span>
                <span class="sr-only">Previous</span>
                </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">4</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">
                    <span>»</span>
                    <span class="sr-only">Next</span>
                </a>
                </li>
            </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bmnc_news/templates/bmnc_news/partials/footer.html
<p>Made by BMNCB14</p>
<p>&copy; Made with Love</p>

bmnc_news/templates/bmnc_news/partials/header.html
<nav class="navbar navbar-expand-md bg-primary navbar-dark">
  <div class="container-fluid">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'bmnc-news:index' %}">
      <img src="https://i.imgur.com/YBdO41f.png" alt="Commercial Photography" width="150"> </a>
    <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
      <ul class="navbar-nav text-light text-center">
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light"data-toggle="modal" data-target=".bs-example-modal-sm"style="font-family:Raleway">Logout</a>
          <div class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-header"><h4>Logout <i class="fa fa-lock"></i></h4>
                  <button type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button></div>
                <div class="modal-body"><i class="fa fa-question-circle"></i> Are you sure you want to log-off?</div>
                <div class="modal-footer"><a href="javascript:;" class="btn btn-primary btn-block">Logout</a></div>
              </div>
            </div>
</div>
        </li>
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light" id ="history" a href="{% url 'bmnc-news:history' %}" style="font-family:Raleway">Polling</a>
        </li>
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light" id ="news"a href="" style="font-family:Raleway">Berita</a>
        </li>
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light" id ="user" href="{% url 'bmnc-news:profile' %}" style="font-family:Raleway">Rio_kurtinus</a>
        </li>
      </ul>

bmnc_news/templates/bmnc_news/profile.html
{% extends "bmnc_news/layout/base.html" %}

{% block content %}

<section name="profile">
    <div class="container" style="margin-top: 75px">
        <h3 id='nama' style="font-weight: bold; text-align: center; margin-bottom: 50px" >Rio Kurtinus</h3>
        <center>
            <span class="glyphicon glyphicon-user" style="font-size: 75px"></span>
        </center>
        <h4 style="text-align: center">Dosen</h4>
        <h4 style="text-align: center">1234567890</h4>
        <hr/ style="border: none; height: 5px; background-color: #FF8260">
        <div class = "col-md-4">
        </div>
        <div class="col-md-3">
            <p>Tempat lahir</p>
            <p>Tanggal lahir</p>
            <p>Email</p>
            <p>Nomor HP</p>
            <p>ID Universitas</p>
        </div>
        <div class="col-md-5">
            <p>Denpasar</p>
            <p>1 Januari 1990</p>
            <p>riokurtinus@gmail.com</p>
            <p>+6281339631789</p>
            <p>53</p>
        </div>
    </div>
</section>

<section name="article" style="margin-top: 50px">
    <h3 style="text-align: center; font-weight: bold">Daftar Artikel</h3>
    <div class="py-5" style="margin-top: 10px">
        <div class="container">
            <div class="col-md-10">
            <h2 class="text-primary">Masih Ada yang Kurang dari Motor Marquez</h2>
            <h5>Posted at 2018-05-05 14:30</h5>
            <p class="" style="text-align: justify; text-justify: inter-word">
                    Marc Marquez tampil begitu mendominasi dalam dua seri terakhir. 
                    Meski demikian, pebalap Repsol Honda itu merasa masih ada yang kurang dari motornya.
                    Setelah start dari pole position dan memenangi MotoGP Austin, 
                    Marquez kembali berjaya di MotoGP Spanyol, Minggu (6/5/2018). 
                    Dia finis terdepan di Sirkuit Jerez meski memulai lomba dari posisi kelima.
            </p>
            </div>
            <div class="col-md-10">
            <h2 class="text-primary">Barca Kian Dekati Gelar Juara La Liga Tanpa Kekalahan</h2>
            <h5>Posted at 2018-05-05 20:30</h5>
            <p class="" style="text-align: justify; text-justify: inter-word">
                    Barcelona baru saja meraih hasil imbang dengan Real Madrid 2-2. 
                    Peluang untuk menjadi juara La Liga tanpa kekalahan kian terbuka.
                    Barca baru saja menyelesaikan pertandingan El Clasico di Camp Nou. 
                    Dalam laga yang bergulir Senin (7/5/2018) dini hari WIB, Barca mendapatkan satu poin.       
            </p>
            </div>
        </div>
    </div>
    
    <div class="py-5" style="margin-left: 550px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <ul class="pagination" >
                    <li class="page-item">
                    <a class="page-link" href="#">
                    <span>«</span>
                    <span class="sr-only">Previous</span>
                    </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">1</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">4</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">
                        <span>»</span>
                        <span class="sr-only">Next</span>
                    </a>
                    </li>
                </ul>
                </div>
            </div>
        </div>
    </div>
</section>
    
    
{% endblock %}

bmnc_news/templates/bmnc_news/riwayat.html
{% extends "bmnc_news/layout/base.html" %}

{% block content %}

<style>

.box {
    transition: box-shadow .3s;
    width: 100%;
    height: 80px;
    margin-top: 25px;
    border-radius:10px;
    border: 1px solid #ccc;
    background: #fff;
    float: left;

}

.box:hover {
    box-shadow: 0 0 80px rgba(33,33,33,.2);
    font-weight: bold
}

.box p {
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 10px;
    font-size: 16px
}
</style>

<section name="polling">
    <div class="container">
        <h3 style="text-align: center; margin-top: 5px; font-weight:bold">Polling Biasa</h3>
        <div class="box">
            <p style="text-align:left">https://wikia.com</p>
            <p style="text-align:right">Kampanye</p>
        </div>
        <div class="box">
            <p style="text-align:left">https://drupal.org</p>
            <p style="text-align:right">Topik Umum</p>
        </div>
        <div class="box">
            <p style="text-align:left">https://discovery.com</p>
            <p style="text-align:right">Tokoh terfavorit</p>
        </div>
        <div class="box">
            <p style="text-align:left">http://imdb.com</p>
            <p style="text-align:right">Kebijakan Publik</p>
        </div>
    </div>
</section>
{% endblock %}

bmnc_sign_up/templates/bmnc_sign_up/cobacoba.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .modal-header, h4, .close {
      background-color: #5cb85c;
      color:white !important;
      text-align: center;
      font-size: 30px;
  }
  .modal-footer {
      background-color: #f9f9f9;
  }
  </style>
</head>
<body>

<div class="container">
  <h2>Modal Login Example</h2>
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-default btn-lg" id="myBtn" data-toggle="modal" data-target="#myModal">Login</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form role="form">
            <div class="form-group">
              <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="text" class="form-control" id="usrname" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="text" class="form-control" id="psw" placeholder="Enter password">
            </div>
            <div class="checkbox">
              <label><input type="checkbox" value="" checked>Remember me</label>
            </div>
              <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
          <p>Not a member? <a href="#">Sign Up</a></p>
          <p>Forgot <a href="#">Password?</a></p>
        </div>
      </div>

    </div>
  </div>
</div>
</body>
</html>

bmnc_sign_up/templates/bmnc_sign_up/partials/footer.html
<p>Made by BMNCB14</p>
<p>&copy; Made with Love</p>